ESHOP3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.cart_detail, name='cart-detail'),
    path('add/<str:product_code>', views.cart_add, name='cart-add'),
    path('remove/<str:product_code>', views.cart_remove, name='cart-remove'),
    path('delete/<str:product_code>', views.cart_remove_one, name='cart-remove-one'),
    path('incr/<str:product_code>', views.cart_add_one, name='cart-add-one')
]

main/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.open_main, name='main'),
    path('news/', views.news_list, name='news'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news-detail')
]

main/models.py
from django.db import models


# Create your models here.


class MainPartner(models.Model):
    name = models.CharField(max_length=200)
    quote = models.CharField(max_length=500)
    text = models.TextField(null=True)
    short_video_link = models.CharField(max_length=500)
    long_video_link = models.CharField(max_length=500)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Слайд_Партнёр'
        verbose_name_plural = 'Слайд_Партнёры'
class MainPartnerImg(models.Model):
    partner = models.ForeignKey(MainPartner, on_delete=models.CASCADE, null=True)
    img = models.ImageField(upload_to='main/img/partners')

    def __str__(self):
        return self.partner.name
    class Meta:
        verbose_name = 'Слайд_Партнёр_Фото'
        verbose_name_plural = 'Слайд_Партнёры_Фото'

class News(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
class NewsImage(models.Model):
    new = models.ForeignKey(News, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='main/img/news')

    def __str__(self):
        return self.new.title

    class Meta:
        verbose_name = 'Превью'
        verbose_name_plural = 'Превью'

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MainPartner, MainPartnerImg, News, NewsImage
from django.views.generic import DetailView


# Create your views here.
def open_main(request):
    partner = MainPartner.objects.all()
    partner_img = MainPartnerImg.objects.all()
    news = News.objects.order_by('-created')[:3]
    news_img = NewsImage.objects.all()

    data = {
        'partner': partner,
        'partner_img': partner_img,
        'news': news,
        'news_img': news_img,
    }
    return render(request, 'main/main_page.html', data)


def news_list(request):
    news = News.objects.all()
    data = {
        'news': news
    }
    return render(request, 'main/news.html', data)


class NewsDetailView(DetailView):
    model = News
    template_name = 'main/details_view.html'
    context_object_name = 'new_post'

main/templates/main/details_view.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{{ new_post.title }}{% endblock %}
{% block content %}
    <div class="detail_container">
        <div class="detail_body">
            <h2>{{ new_post.title|safe }}</h2>
            <p>{{ new_post.text|safe }}</p>
            Опубликовано: {{ new_post.created|date:"d/m/Y"|safe }}
        </div>
        <button onclick="goBack()">Назад</button>
    </div>
    <script>
    function goBack() {
        window.history.back();
    }
    </script>
{% endblock %}

main/templates/main/news.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Новости{% endblock %}
{% block content %}
    <div class="main_news_container">
        <h1>НОВОСТИ</h1>
        <div class="main_news_body">
            {% for new_obj in news %}
                <a class="new" href="{% url 'news-detail' new_obj.id %}">
                    {% for new_obj_img in new_obj.newsimage_set.all %}<img src="{{ new_obj_img.img.url }}" alt="">{% endfor %}
                    <h3>{{ new_obj.title }}</h3>
                </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}