ESHOP3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.cart_detail, name='cart-detail'),
    path('add/<str:product_code>', views.cart_add, name='cart-add'),
    path('remove/<str:product_code>', views.cart_remove, name='cart-remove'),
    path('delete/<str:product_code>', views.cart_remove_one, name='cart-remove-one'),
    path('incr/<str:product_code>', views.cart_add_one, name='cart-add-one')
]

shop/urls.py
from django.urls import path, include
from . import views
from favorites import views as f_views
urlpatterns = [
    path('', views.show_categories, name='assortment'),
    path('assortment/<str:category_slug>', views.show_category_assortment, name='assortment-by-category'),
    path('assortment/<str:category_slug>/<str:oiltype_slug>', views.show_category_assortment, name='assortment-by-category-oiltype'),
    path('assortment/<str:category_slug>/<str:oiltype_slug>/<str:viscosity_slug>', views.show_category_assortment, name='assortment-by-category-oiltype-viscosity'),
    path('assortment/<str:category_slug>/<str:oiltype_slug>/<str:viscosity_slug>/<str:compound_slug>', views.show_category_assortment, name='assortment-by-category-oiltype-viscosity-compound'),
    path('assortment/<str:category_slug>/<str:oiltype_slug>/<str:viscosity_slug>/<str:compound_slug>/<str:fuel_slug>', views.show_category_assortment, name='assortment-by-category-oiltype-viscosity-compound-fuel'),
    path('assortment/<str:category_slug>/<str:oiltype_slug>/<str:viscosity_slug>/<str:compound_slug>/<str:fuel_slug>/<str:transmission_slug>',
         views.show_category_assortment, name='assortment-by-category-oiltype-viscosity-compound-fuel-transmission'),

    path('product/<str:product_code>', views.show_product_detail, name='product-detail'),
    path('product/<str:product_code>/add-to-favorite/', f_views.add_to_favorites, name='add_to_favorites'),
    path('search/', views.Search.as_view(), name='search'),
    path('search/<int:page>', views.Search.as_view(), name='search-page'),
    path('contact/', views.show_contact_page, name='contacts'),
    path('about/', views.show_about_page, name='about'),
    path('partners/', views.show_partners, name='partners'),
    path('partners/<int:partner_id>', views.show_one_partner, name='one-partner')

]

shop/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('assortment-by-category', args=[self.slug])


class CategoryImage(models.Model):
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='shop/img/categories')

class Brand(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()

    def __str__(self):
        return self.name



class OilType(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Viscosity(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ManyToManyField(Category)
    oiltype = models.ManyToManyField(OilType)

    def __str__(self):
        return self.name


class Compound(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ManyToManyField(Category)
    oiltype = models.ManyToManyField(OilType)
    viscosity = models.ManyToManyField(Viscosity)

    def __str__(self):
        return self.name


class Fuel(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ManyToManyField(Category)
    oiltype = models.ManyToManyField(OilType)
    viscosity = models.ManyToManyField(Viscosity)
    compound = models.ManyToManyField(Compound)

    def __str__(self):
        return self.name
class Transmission(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ManyToManyField(Category)
    oiltype = models.ManyToManyField(OilType)
    viscosity = models.ManyToManyField(Viscosity, blank=True)
    compound = models.ManyToManyField(Compound, blank=True)
    fuel = models.ManyToManyField(Fuel, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    code = models.CharField(max_length=100, primary_key=True, default=0, db_index=True)
    vendor_code = models.CharField(max_length=100, unique=True, null=True, blank=True, db_index=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    name_m = models.CharField(max_length=200, null=True, db_index=True)
    name = models.CharField(max_length=200, db_index=True)
    visual_name = models.CharField(max_length=200, null=True, blank=True)
    category = models.ManyToManyField(Category)
    oiltype = models.ForeignKey(OilType, on_delete=models.CASCADE, blank=True, null=True, default='-')
    viscosity = models.ManyToManyField(Viscosity, blank=True, null=True, default='-')
    compound = models.ForeignKey(Compound, on_delete=models.CASCADE, blank=True, null=True, default='-')
    fuel = models.ManyToManyField(Fuel, blank=True, default='-')
    transmission = models.ManyToManyField(Transmission, blank=True, default='-')
    volume = models.IntegerField(null=True, blank=True, default='-')
    related_products = models.ManyToManyField('self', blank=True)
    description = models.TextField(null=True, blank=True, default='-')
    stock = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    security_pasport = models.CharField(max_length=300, null=True, blank=True)
    tech_desc = models.CharField(max_length=300, null=True, blank=True)
    is_favorite = models.BooleanField(default=False)
    img = ProcessedImageField(upload_to='shop/img/products',
                              processors=[ResizeToFit(245.69, 317.97)],
                              options={'quality': 90},null=True, blank=True)

    def __str__(self):
        return self.code

    def get_url(self):
        return reverse('product-detail', args=[self.code])


class Partner(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    link = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('one-partner', args=[self.id])



class PartnerImage(models.Model):
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, null=True)
    img = models.ImageField(upload_to='shop/img/partners')

    def __str__(self):
        return self.partner.name


class User_Request(models.Model):
    full_name = models.CharField('ФИО', max_length=300)
    company = models.CharField('Название организации', max_length=300, blank=True)
    position = models.CharField('Должность', max_length=300, blank=True)
    email = models.EmailField('Почта')
    phone = models.CharField('Номер телефона', max_length=20)
    subject = models.CharField('Тема сообщения', max_length=150)
    text = models.TextField()

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

shop/forms.py
from .models import User_Request
from django import forms

class User_RequestForm(forms.ModelForm):
    class Meta:

        model = User_Request
        fields = ['full_name', 'company', 'position', 'email', 'phone', 'subject', 'text']

        widgets = {
            'full_name': forms.TextInput(attrs={
                'placeholder': '*ФИО',
                'data-no-numbers': True,
            }),
            'company': forms.TextInput(attrs={
                'placeholder': 'Название организации',
                'id': 'text_input'
            }),
            'position': forms.TextInput(attrs={
                'placeholder': 'Должность',
                'data-no-numbers': True,
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Почта'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder':'*Телефон',
                'id':'user_phone_input',
                'class':'phone_number',
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': '*Тема сообщения'
            }),
            'text': forms.Textarea(attrs={
                'placeholder': '*Сообщение'
            })
        }

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Brand, OilType, Viscosity, Compound, Fuel, Transmission, Product, Partner, PartnerImage
from cart.forms import CartAddProductForm
from django.views.generic import ListView
from .forms import User_RequestForm
from django.db.models import Q
from django.core.mail import send_mail


# Create your views here.
def show_categories(request):
    categories = Category.objects.all()
    data = {
        'categories': categories,
    }
    return render(request, 'shop/categories.html', data)


def show_category_assortment(request, category_slug=None, oiltype_slug=None, viscosity_slug=None,
                             compound_slug=None, fuel_slug=None, transmission_slug=None):
    category = None
    oil_type = None
    visc = None
    comp = None
    fuel = None
    transmission = None
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category, available=True)
    if oiltype_slug:
        oil_type = get_object_or_404(OilType, slug=oiltype_slug)
        products = Product.objects.filter(category=category, oiltype=oil_type, available=True)
    if viscosity_slug:
        visc = get_object_or_404(Viscosity, slug=viscosity_slug)
        products = Product.objects.filter(category=category, oiltype=oil_type, viscosity=visc, available=True)
    if compound_slug:
        comp = get_object_or_404(Compound, slug=compound_slug)
        products = Product.objects.filter(category=category, oiltype=oil_type, viscosity=visc, compound=comp,
                                          available=True)
    if fuel_slug:
        fuel = get_object_or_404(Fuel, slug=fuel_slug)
        products = Product.objects.filter(category=category, oiltype=oil_type, viscosity=visc, compound=comp, fuel=fuel,
                                          available=True)
    if transmission_slug:
        transmission = get_object_or_404(Transmission, slug=transmission_slug)
        products = Product.objects.filter(category=category, oiltype=oil_type, viscosity=visc, compound=comp, fuel=fuel,
                                          transmission=transmission,
                                          available=True)

    data = {
        'category': category,
        'oil_type': oil_type,
        'visc': visc,
        'comp': comp,
        'fuel': fuel,
        'transmission': transmission,
        'products': products,

    }
    return render(request, f'shop/product_list.html', data)


def show_product_detail(request, product_code: str):
    product = get_object_or_404(Product, code=product_code)
    cart_product_form = CartAddProductForm()
    related_products = product.related_products.all()
    data = {
        'product': product,
        'cart_product_form': cart_product_form,
        'related_products': related_products,
    }

    return render(request, 'shop/product_detail.html', data)


def show_contact_page(request):
    error = ''
    if request.method == 'POST':
        contact_form = User_RequestForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            subject = 'Новая заявка'
            message = 'Вам поступила новая заявка. Проверьте панель администратора'
            from_email = 'no-reply.sevsnab@mail.ru'
            to_email = ['seversnab-info@yandex.ru']
            send_mail(subject, message, from_email, to_email, fail_silently=True)
            return redirect('contacts')
        else:
            error = 'Данные введены некорректно'
    contact_form = User_RequestForm()
    data = {
        'contact_form': contact_form
    }
    return render(request, 'shop/contact_us.html', data)


def show_about_page(request):
    return render(request, 'shop/about.html')


def show_partners(request):
    partners = Partner.objects.all()
    data = {
        'partners': partners,
    }
    return render(request, 'shop/partners.html', data)


def show_one_partner(request, partner_id: int):
    partner = get_object_or_404(Partner, id=partner_id)
    img = get_object_or_404(PartnerImage, id=partner_id)
    data = {
        'partner': partner,
        'partner_img': img,
    }
    return render(request, 'shop/one_partner.html', data)


class Search(ListView):
    model = Product
    template_name = 'shop/search_results.html'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            queryset = Product.objects.filter(
                Q(name__icontains = query)|Q(viscosity__name__icontains=query)
            )
        else:
            queryset = Product.objects.none()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} О нас {% endblock %}
{% block content %}
    <div class="about_container">
        <div class="about_body">
            <h2>Добро пожаловать!</h2>
            <div class="about_text_block">
                <div class="about_text_layer1">
                    <p>
                        На сегодняшний день мы работаем с крупными предприятиями по <b>Северо-Западному округу</b>.
                        Наша компания
                        имеет складские помещения, позволяющие закрывать Ваши потребности на следующий день, и
                        собственный
                        транспорт. Также наша компания зарегистрирована на многих площадках и принимает участие во
                        многих
                        конкурсах (тендерах), а также и прямые договора на поставку продукции. Помимо этого наша
                        компания
                        готова предложить <i>услуги по утилизации отработанных масел</i>.
                    </p>
                    <img src="{% static 'shop/img/about_layer1.jpg' %}" alt="">

                </div>
                <div class="about_text_layer2">
                    <p>
                        <b>ООО "Северснаб"</b> зарегистрирован 05.08.2014 г., работает в сфере реализации ГСМ и
                        фильтров. На
                        сегодняшний день компания является официальным дилером крупнейшего производителя по маслам и
                        смазкам
                        <b>North Sea Lubricants (Голландия)</b>, <b>Ymioil(Тюмень)</b> , представляет интересы компании
                        <b>Delfin
                            Group,
                            Nordfil (фильтра)</b>. Также наша компания занимается разработкой и производством фильтров
                        для
                        спецтехники и легкового транспорта. Помимо этого в ассортимент нашей компании входят такие
                        бренды,
                        как <b>Газпромнефть, Лукойл, Роснефть</b> и др. производители.
                    </p>
                    <img src="{% static 'shop/img/about_layer2.jpg' %}" alt="">
                </div>
                <h1>Сертификаты</h1>
                <div class="certificates">

                    <div class="slider">
                        <div class="slider-wrapper">
                            <div class="slide1-content">
                                <img src="{% static 'shop/img/YMICert.png' %}" alt="Slide1">
                                <img src="{% static 'shop/img/NSLcert.png' %}" alt="Slide2">
                                <p>ООО "Северснаб" является официальным дилером производителей по маслам. Подтверждением
                                    являются предоставленные, компаниями-партнерами сертификаты!</p>
                            </div>
                            <div class="slide2-content">

                            </div>

                        </div>
                        <div class="slider-controls">
                            <button class="slider-prev">&#8249;</button>
                            <button class="slider-next">&#8250;</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/categories.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Категории {% endblock %}
{% block pagename %}<h1 class="category_heading">Ассортимент</h1> {% endblock %}
{% block content %}
    <div class="category_container">
        <div class="category_body">
            {% for category in categories %}
                <div class="category_card_container">
                    <div class="category_card_body">
                        <a class="category" href="{{ category.get_url }}">
                            {% for catimg in category.categoryimage_set.all %}
                                <img src='{{ catimg.img.url }}' alt="">
                            {% endfor %}
                        <p>{{ category }}</p>
                    </a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
    <div class="ask">
        <div class="ask_body">
            <div class="ask_sentence">
                <p>Есть вопросы? Наши специалисты ответят!</p>
            </div>

                <a class="ask_button" href="{% url 'contacts' %}">Написать письмо</a>
        </div>
    </div>



{% endblock %}

shop/templates/shop/contact_us.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Контакты {% endblock %}

{% block content %}
    <div class="contact_us_container">
        <div class="contact_us_body">
            <div class="contact_us_form">
                <h1>напишите нам!</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ contact_form.full_name }}
                    {{ contact_form.company }}
                    {{ contact_form.position }}
                    {{ contact_form.email }}
                    {{ contact_form.phone }}
                    {{ contact_form.subject }}
                    {{ contact_form.text }}
                    <input class="submit_form" type="submit" value="отправить">
                </form>
            </div>
            <div class="contact_us_initials">
                <div class="map">
                    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A8f8d44ebac29f057b438b0fbec53fb5d69d5043d76d49fbc86d25d1ae69a7012&amp;width=100%25&amp;height=583&amp;lang=ru_RU&amp;scroll=true"></script>
                </div>
                <div class="initials">
                    <div class="initial_container">
                        <div class="initial_body">
                            <h1>контакты</h1>
                            <a href="" class="callback"></a>
                        </div>
                    </div>
                    <div class="initial_container">
                        <div class="initial_body">
                            <h1>Адрес офиса</h1>
                            <p>Россия, Лен.область, г. Гатчина, ул. Рысева д. 62А</p>
                        </div>
                    </div>
                    <div class="initial_container">
                        <div class="initial_body">
                            <div class="initial_block">
                                <h1>Номер телефона</h1>
                                <a href="tel:+78122971515" style="text-align: center">+7 (812) 297-15-15</a>
                            </div>
                            <div class="initial_block">
                                <h1>Почта</h1>
                                <a href="mailto: info@sev_snab.ru" style="text-align: center">info@sev_snab.ru</a>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/one_partner.html
{% extends "shop/base.html" %}
{% block title %}{{ partner.name }}{% endblock %}
{% block content %}
    <div class="partner_container">
        <div class="partner_body">
            <img src="{{ partner_img.img.url }}" alt="hgg">
        <h2>{{ partner.name }}</h2>
            <div class="partner_text">
                <h2>О бренде</h2>
                {{ partner.description|safe }}
                <a href="{{ partner.link }}"><i class="fa-solid fa-globe"></i>{{ partner.link }}</a>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/partners.html
{% extends 'shop/base.html' %}
{% block title %}Наши партнёры{% endblock %}
{% block content %}
    <div class="intro_container">
        <div class="intro_body">
            <h2>предисловие</h2>
            <div class="intro_text">
                <p>На протяжении многих лет наша компания создавала сеть ценных ключевых партнеров и гордится длительным
                    сотрудничеством друг-с-другом. Каждый партнер является престижным брендом со всемирной репутацие в
                    своей сфере деятельности.</p>
                <p>В связи с этим мы хотим предложить Вам познакомиться с каждым партнёром индивидуально.</p>
            </div>
        </div>
    </div>
    <div class="partners_container">

        <div class="partners_body">
            {% for partner in partners %}
            <a class="partners" href="{{ partner.get_url }}">
                {% for partimg in partner.partnerimage_set.all %}
                <img src="{{ partimg.img.url }}" alt="">
                {% endfor %}
            </a>
        {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% block title %}{{ category.name }}{% endblock %}
{% block pagename %}<h1>{{ category.name }}</h1>{% endblock %}
{% block content %}
    <div class="list_container">
        <div class="list_body">
            <aside>
                <div class="aside-body">
                    <div class="filter_block">
                        <h2>Тип продукта</h2>
                        <ul>
                            {% for oiltype in category.oiltype_set.all %}
                                <li>
                                    <a href="{{ category.get_url }}/{{ oiltype.slug }}">{{ oiltype }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% if oil_type %}
                        <div class="filter_block">
                            <h2>Вязкость</h2>
                            <ul>
                                {% for viscosity in oil_type.viscosity_set.all %}
                                    <li>
                                        <a href="{{ category.get_url }}/{{ oil_type.slug }}/{{ viscosity.slug }}">{{ viscosity }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if visc %}
                        <div class="filter_block">
                            <h2>Состав</h2>
                            <ul>
                                {% for compound in visc.compound_set.all %}
                                    <li>
                                        <a href="{{ category.get_url }}/{{ oil_type.slug }}/{{ visc.slug }}/{{ compound.slug }}">{{ compound }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if comp %}
                        <div class="filter_block">
                            <h2>Топливо</h2>
                            <ul>
                                {% for fuel in category.fuel_set.all %}
                                    <li>
                                        <a href="{{ category.get_url }}/{{ oil_type.slug }}/{{ visc.slug }}/{{ comp.slug }}/{{ fuel.slug }}">{{ fuel }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </aside>
            <div class="container mt-2">
                <h2>Товары</h2>
                <div class="product-list-container">
                    <div class="product-list-body">
                        <div class="product-list-bbody">
                            {% for product in products %}
                                <div class="product-card-container">
                                    <div class="product-card-body">
                                        {% if product.img %}<img src="{{ product.img.url }}" alt="">{% endif %}
                                        <div class="card-body">
                                            {% if product.is_favorite %}
                                                <a class="is-favorite" href="{% url 'add_to_favorites' product.code %}">
                                                    <i class="fa-solid fa-star" style="color: #ffd041"></i></a>
                                            {% else %}
                                                <a class="is-favorite" href="{% url 'add_to_favorites' product.code %}">
                                                    <i class="fa-solid fa-star" style="color: #919191"></i></a>
                                            {% endif %}
                                            <h5 class="card-title">{{ product.visual_name }}</h5>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group">
                                                    <a href="{{ product.get_url }}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                                </div>
                                                <small class="text-muted">{{ product.price }} руб.</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/search_results.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Результат поиска {% endblock %}
{% block content %}

    <div class="search-results">
        <div class="search-results-body">
        <h3>Результат поиска:</h3>

            <div class="row mt-5 mb-3">
                {% for product in page_obj %}
                    <div class="col-lg-4 col-md-5 col-sm-6">
                        <div class="card mb-3 box-shadow">
                            {% if product.img %}
                                <img src="{{ product.img.url }}" alt="" class="card-img-top">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ product.visual_name }}</h5>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ product.get_url }}"
                                           class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                    </div>
                                    <small class="text-muted">{{ product.price }} руб.</small>
                                </div>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="pagination-block">
        <div class="pagination-block-body">
            <nav aria-label="...">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a
                                href="{% url 'search-page' page_obj.previous_page_number %}?q={{ q }}"
                                class="page-link"><i class="fa-solid fa-arrow-left"></i></a></li>
                    {% else %}
                        <li class="page-item disabled"><a href="#" class="page-link"><i class="fa-solid fa-arrow-left"></i></a></li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><a class="page-link" href="#">{{ i }} <span
                                    class="sr-only">(текущая)</span></a></li>
                        {% else %}
                            <li class="page-item"><a href="{% url 'search-page' i %}?q={{ q }}"
                                                     class="page-link">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a
                                href="{% url 'search-page' page_obj.next_page_number %}?q={{ q }}"
                                class="page-link"><i class="fa-solid fa-arrow-right"></i></a></li>
                    {% else %}
                        <li class="page-item disabled"><a href="#" class="page-link"><i class="fa-solid fa-arrow-right"></i></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>



{% endblock %}